# path to the task data directory
log_level: "DEBUG"

desc_file: idea_example.json
workspace_dir: workspaces
log_dir: "workspaces/logs"

exp_name: run # a random experiment name will be generated if not provided

# settings for code execution
exec:
  timeout: 7200
  agent_file_name: runfile.py
  format_tb_ipython: False

generate_report: True
# LLM settings for final report from journal
report:
  model: Qwen/Qwen2.5-VL-7B-Instruct
  temp: 1.0

# LLM settings for paper writeup
writeup:
  model: Qwen/Qwen2.5-VL-7B-Instruct
  plot_model: Qwen/Qwen2.5-VL-7B-Instruct
  citation_model: Qwen/Qwen2.5-VL-7B-Instruct
  temperature: 1.0
  writeup_type: normal
  writeup_retries: 3
  num_cite_rounds: 5

review:
  model: Qwen/Qwen2.5-VL-7B-Instruct
  temperature: 1.0

experiment:
  num_syn_datasets: 1

# agent hyperparams
agent:
  type: parallel
  num_workers: 1
  stages:
    stage1_max_iters: 16
    stage2_max_iters: 10
    stage3_max_iters: 8
    stage4_max_iters: 14
  # how many improvement iterations to run
  steps: 5 # if stage-specific max_iters are not provided, the agent will use this value for all stages
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 1
  multi_seed_eval:
    num_seeds: 1 # should be the same as num_workers if num_workers < 3. Otherwise, set it to be 3.

  # LLM settings for coding
  code:
    model: Qwen/Qwen2.5-VL-7B-Instruct
    temp: 1.0

  # LLM settings for evaluating program output / tracebacks
  feedback:
    model: Qwen/Qwen2.5-VL-7B-Instruct
    temp: 0.5

  vlm_feedback:
    model: Qwen/Qwen2.5-VL-7B-Instruct
    temp: 0.5

  search:
    max_debug_depth: 5  # increased from 3 - try harder to debug
    debug_prob: 0.7     # increased from 0.5 - debug more often
    num_drafts: 3
