services:
  db:
    image: ankane/pgvector
    container_name: ae_scientist_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: ae_scientist_db
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_DATA_DIR:-./.docker/postgres}:/var/lib/postgresql/data"
volumes:
  postgres_data:

